name: tawsela_app
description: "Tawsela"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: any
  flutter_bloc: any
  geolocator: any
  geocoding: any
  google_maps_flutter: any
  flutter_polyline_points: any
  google_places_flutter: any
  places_service: any
  google_directions_api: any
  dio: any
  intl: any
  flutter_localizations:
    sdk: flutter
  json_serializable: any
  json_annotation: any
  another_flushbar: any
  # google_distance_matrix: any
  equatable: any
  http: any
  connectivity: any
  get_it: any
  cupertino_icons: any
  top_modal_sheet: any
  image_picker: any
  image_cropper: any
  permission_handler: any
  shared_preferences: any
  popover: any
  flutter_svprogresshud: any
  meta: any
  html: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  flutter_lints: any

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/JSON/keys/server_url.json
    - assets/JSON/keys/google_map_key.json
    - assets/JSON/paths/3.json
    - assets/JSON/paths/9.json
    - assets/JSON/paths/7.json
    - assets/JSON/paths/11.json
    - assets/1.png
    - assets/2.png
    - assets/3.png
    - assets/4.png
    - assets/5.png
    - assets/6.png
    - assets/8.png
    - assets/9.png
    - assets/11.png
    - assets/17.png

  fonts:
    - family: Alexandria
      fonts:
        - asset: assets/fonts/Alexandria-VariableFont_wght.ttf
    - family: CustomGoogleIcon
      fonts:
        - asset: assets/custom_icons/CustomGoogleIcon.ttf
    - family: CustomSwitchIcon
      fonts:
        - asset: assets/custom_icons/CustomSwitchIcon.ttf
flutter_intl:
  enabled: true